### ISSUE TITLE
提供linux包可以吗？

### ISSUE THREAD

**Issue by jingle0927** [trazyn/weweChat#10]
Electronic WeChat 以前一直用这个，今天突然看到这个，但是颜值没有大神这个高。

**Comment by trazyn** [comment]
https://github.com/trazyn/weweChat/releases/download/1.0.0/wewechat-1.0.0-x86_64.AppImage
试试

**Comment by trazyn** [comment]
https://github.com/trazyn/weweChat/releases/download/1.0.0/wewechat-1.0.0-x86_64.AppImage
