### ISSUE TITLE
多选消息后合并转发, 怎么获取这个内容?

### ISSUE THREAD

**Issue by gclsoft** [trazyn/weweChat#108]
![image](https://user-images.githubusercontent.com/1269898/35190712-9ddf3aae-fea2-11e7-9d3b-c6bfd53d8f16.png)
多选消息后合并转发, 怎么收到并获取这个内容, 现在提示的是:"该类型暂不支持,请在手机上查看"
但是我用电脑版的微信就是支持的.

**Comment by trazyn** [comment]
微信Web API有些和桌面以及手机的不一样，有些消息类型是不支持的
