### ISSUE TITLE
[Windows 10] send messeges successfully, but can't receive any messeges

### ISSUE THREAD

**Issue by Deardrops** [trazyn/weweChat#11]
系统：windows 10 14393
版本：wewechat 1.0.0
问题描述：成功登陆，打开一个新的聊天窗口，可以向别人发送消息，但是无法收到别人发出的消息。
手机上可以看到别人发送的消息。

**Comment by trazyn** [comment]
我也发现了，手机和mac端交叉使用时候有时候心跳会断掉，导致消息接收失败

**Comment by Deardrops** [comment]
心跳正常，devtools输出没有异常。
selector = 2，可以正常接收消息。
bug无法复现。😥

**Comment by trazyn** [comment]
更新比较频繁，下载的exe可能都不是最新的
