### ISSUE TITLE
消息提示音

### ISSUE THREAD

**Issue by yangke9** [trazyn/weweChat#112]
是够可以增加消息提示音，现在收消息有点不知道到底发了没有。

谢谢开发者

**Comment by amitbha** [comment]
开发者已跑路，建议楼主 fork 出来自己开发。

**Comment by trazyn** [comment]
一直都有提示，除了三种情况：
1. 设置发送方不提示
2. 消息是自己发送的，比如从手机上同步过来的
3. 设置了不提示
![screen shot 2018-07-25 at 10 44 13 pm](https://user-images.githubusercontent.com/1774898/43211148-6e01f47c-9063-11e8-9ba3-298746aae2dc.png)
