### ISSUE TITLE
uses too much ram and cpu

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [trazyn/weweChat#12]
pls fix

**Comment by trazyn** [comment]
![screen shot 2017-08-27 at 7 44 07 pm](https://user-images.githubusercontent.com/1774898/29749501-21d23c78-8b60-11e7-85ad-bbababad68d9.png)

what's your platform, on my osx it looks work well

**Comment by MegaApuTurkUltra** [comment]
what about ram?

**Comment by ysh329** [comment]
So embarrassing it is. It's normal to consume much RAM due to Electron.

**Comment by trazyn** [comment]
This is super awkward, Electron use much RAM is normal

**Comment by MegaApuTurkUltra** [comment]
ok, so can you use some other platform that isn't a resource hog? my 2005 thinkpad is struggling to run this

**Comment by yuanchenxi95** [comment]
Can you just buy anew laptop?

**Comment by MegaApuTurkUltra** [comment]
umm macbooks are very expensive and i can't run libreboot on them

**Comment by ysh329** [comment]
@MegaApuTurkUltra You can consider other wechat projects using search of Github. I remember a wechat client on Github have 8000+ stars in another repo.
