### ISSUE TITLE
发生文件时候提示失败

### ISSUE THREAD

**Issue by jingle0927** [trazyn/weweChat#16]
![_ _20170828111021](https://user-images.githubusercontent.com/26103116/29757858-ac45521a-8be1-11e7-8dce-df2c8e73a8a6.png)

linux平台

**Comment by jingle0927** [comment]
运行时候 有2个wewechat 标题。

**Comment by trazyn** [comment]
文件无法发送 -> 这个微信不允许上传空文件，需要优化提示内容
两个标题 -> 目前主要在mac上开发，其他系统的ui没这么优化
收不到消息 -> 看看devtools里面心跳的返回收正确，selector = 2的时候表示收到消息

**Comment by trazyn** [comment]
某些敏感内容被拉黑文件也是无法上传的，比如 [zhao](https://github.com/programthink/zhaol)这个里面的内容
