### ISSUE TITLE
css报错怎么在webstorm里屏蔽?

### ISSUE THREAD

**Issue by gclsoft** [trazyn/weweChat#167]
![image](https://user-images.githubusercontent.com/1269898/44508925-9f494900-a6e2-11e8-995d-5688a07339fe.png)
.eslintignore文件里也加了*.css 不起作用

**Comment by trazyn** [comment]
样式的校验是stylelint

**Comment by gclsoft** [comment]
已解决, 设置里将css移到pcss里就行
