### ISSUE TITLE
同步接口问题

### ISSUE THREAD

**Issue by flyfei** [trazyn/weweChat#17]
你好，发现两个接口问题：
1: webwxbatchgetcontact 接口，有时候会一直刷，一秒几十次，复现概率挺高得，好像和多个人或群聊天就会复现。
2: synccheck接口 status 显示为 finished 时，收不到数据了，必须重启软件才可以继续使用

**Comment by trazyn** [comment]
这个接口是收到10000类型消息时候去调用的，10000号消息已知是群组信息发生变化时候接收到的，此时会调用webwxbatchgetcontact 去更新群组信息

**Comment by flyfei** [comment]
synccheck  自己会 finish掉，这个是个 bug？

**Comment by trazyn** [comment]
怎么重新这个问题

**Comment by flyfei** [comment]
这会儿没复现，你需要什么数据，http的相关信息？
那会儿记得看finish的那个 http信息。preview 里面是乱码，之前的没有乱码。

**Comment by trazyn** [comment]
synccheck 那个接口返回乱码基本上是被服务器端给断开了，这个时候应该是被catch到然后刷新页面显示二维码要重新登录

**Comment by flyfei** [comment]
电脑休眠后、再唤醒后，程序不执行同步方法。 synccheck 状态 为 canceled。webwxsync 状态 为 failed。


详细synccheck http 信息：

Request URL:https://webpush.wx.qq.com/cgi-bin/mmwebwx-bin/synccheck?r=1503917281285&sid=gTcWMk%2BQqlRFu0bp&uin=2122697401&skey=@crypt_f0c68b43_1b55a05c79b795d36230a09fcb645b5a&synckey=1_656774374%7C2_656775157%7C3_656774921%7C11_656775155%7C13_656570222%7C201_1503917203%7C203_1503916880%7C1000_1503913142%7C1001_1503913173%7C1002_1503481241
Request Headers
Provisional headers are shown
Accept:application/json, text/plain, */*
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) wewechat/1.0.0 Chrome/56.0.2924.87 Electron/1.6.11 Safari/537.36
Query String Parameters
view source
view URL encoded
r:1503917281285
sid:gTcWMk+QqlRFu0bp
uin:2122697401
skey:@crypt_f0c68b43_1b55a05c79b795d36230a09fcb645b5a
synckey:1_656774374|2_656775157|3_656774921|11_656775155|13_656570222|201_1503917203|203_1503916880|1000_1503913142|1001_1503913173|1002_1503481241

**Comment by flyfei** [comment]
synccheck 方法状态 为  finished复现了。
http信息

Request URL:https://webpush.wx.qq.com/cgi-bin/mmwebwx-bin/synccheck?r=1503922132609&sid=3tsNm8iiTp75tAtY&uin=2122697401&skey=@crypt_f0c68b43_7cc4145979ecfbc8ab5590e7c4756978&synckey=1_656774374%7C2_656775226%7C3_656774921%7C11_656775184%7C13_656570222%7C201_1503922133%7C203_1503917840%7C1000_1503913142%7C1001_1503913173%7C1002_1503481241
Remote Address:182.254.78.160:443
Response Headers
view source
Connection:keep-alive
Content-Length:42
Request Headers
view source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN
Connection:keep-alive
Cookie:webwxuvid=c49917ba25d8423927f5ac3533e0b15332bed679099c07df2d82874f9c29a9af3f8c30d691c2d22e3036b5d1349ee6ab; mm_lang=en_US; webwx_auth_ticket=CIsBEOqZuGgagAFy+wAttwWmkv0XVJ97z0o8X5eJ8V8MjGTwWZRG570P3OugaCAe8uKox+TZpu5df4/ogjtX5vduj2iK5y0gAWKPovbMuKNY9yfAwUFF7P0F+9y68BOSAg3+BENrHsjmOcku6yDdbd+INTmwTgHTZXfSqSZYJakeNM1osTUB/g36BQ==; wxloadtime=1503922060_expired; wxpluginkey=1503913142; wxuin=2122697401; wxsid=3tsNm8iiTp75tAtY; webwx_data_ticket=gScH9Dv4cW7K/izMVBxMaSUK
Host:webpush.wx.qq.com
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) wewechat/1.0.0 Chrome/56.0.2924.87 Electron/1.6.11 Safari/537.36
Query String Parameters
view source
view URL encoded
r:1503922132609
sid:3tsNm8iiTp75tAtY
uin:2122697401
skey:@crypt_f0c68b43_7cc4145979ecfbc8ab5590e7c4756978
synckey:1_656774374|2_656775226|3_656774921|11_656775184|13_656570222|201_1503922133|203_1503917840|1000_1503913142|1001_1503913173|1002_1503481241



respoose 信息：
oöÂxÝ`¾þ+CÉP-}ÃÁ+po²÷ÿ¹¤%Ë³SjÐW6

**Comment by trazyn** [comment]
晚点重新打包上去，你的这个错误没catch到目测是版本问题，目前更新比较频繁，打包的文件没有区分版本

**Comment by trazyn** [comment]
@flyfei https://github.com/trazyn/weweChat/releases/download/1.0.0/wewechat-1.0.0-mac.dmg

**Comment by trazyn** [comment]
synccheck 有时候会假死，一直pending 目前还不知道是什么原因导致的

**Comment by flyfei** [comment]
webwxbatchgetcontact 方法一直在请求，允许两三分钟，请求进2000次了，
 response 都是 
{
"BaseResponse": {
"Ret": 1205,
"ErrMsg": ""
}
,
"Count": 0,
"ContactList": []
}

参数  r一直在增加 r:1504078522534

**Comment by trazyn** [comment]
这个接口调用太频繁会出现1205，群组更新后会收到10000，此时更新后的群组信息会在下一个sync中返回，但是这个会有几秒的延时，代码中为了达到立即更新的效果所以调用了这个接口，所以调用的太多了，然后就1205了😂，
昨天晚上已经更新了代码，不会调用这个接口刷新群组，而是等待服务器端的返回，你下载最新的dmg就好了，但是可能你的web
微信短时间内不可用，需要等这个接口不返回1205 一般几个小时吧，反则你登录上去看不到群里面的成员的

**Comment by flyfei** [comment]
`Failed to get chat room member` 也一直在刷，是不是跟这个有关系？

**Comment by trazyn** [comment]
是的，你的dmg不是最新的，老代码会调用这个接口刷群组信息，出现1205就一直刷这个错误
