### ISSUE TITLE
提点小建议

### ISSUE THREAD

**Issue by leibnizl** [trazyn/weweChat#18]
1. 在群聊里面，默认没有显示群昵称，这个着实不太方便，群聊人数比较多时，光看头像无法识别是谁在发言。
2. 关于显示No Chat Selected。在本来已经选择一个聊天的时候，若点击左下方的Contacts或Settings，然后在点左下角的Chat时，就会显示No Chat Selected，而不是上次已经选择的聊天或者最上方的聊天。不知道No Chat Selected这个是不是有意这么做的，若是有意这么做的，完全看个人习惯，这个建议可以忽略。

**Comment by trazyn** [comment]
1. 主要是ui展示美观问题，所以没加上去，晚点增加个设置是否显示用户名称吧
2. 这个确实是个人习惯，后面增加选项记住上一个会话

**Comment by leibnizl** [comment]
OK，作者辛苦了。

**Comment by trazyn** [comment]
@leibnizl https://github.com/trazyn/weweChat/releases/download/1.0.0/wewechat-1.0.0-mac.dmg
