### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [trazyn/weweChat#192]
Hi @trazyn . I'm a graphic designer and an open source enthusiast. I would like to contribute to your project by proposing a logo/icon design. If you need to make some change please let me know. 
![wewechat](https://user-images.githubusercontent.com/36124339/47492368-0caa5f00-d877-11e8-91e0-6c276fd3883e.png)
Best Regard. Mirza Zulfan

**Comment by trazyn** [comment]
Thanks

**Comment by mirzazulfan** [comment]
Should i create a pr @trazyn ? Thanks
