### ISSUE TITLE
weweChat can not start on Ubuntu 18.10

### ISSUE THREAD

**Issue by 3lackrush** [trazyn/weweChat#213]
weweChat can not start on Ubuntu 18.10

**Comment by ukhack** [comment]
+1

**Comment by Espylapiza** [comment]
[1]    25790 segmentation fault (core dumped)  wewechat

+1

**Comment by zzhiyi** [comment]
Duplicate of https://github.com/trazyn/weweChat/issues/196

**Comment by fengye0907** [comment]
can't start on Ubuntu 19 as well
