### ISSUE TITLE
有时候会出现掉线的情况，不会自动跳转重新登陆，必须得重新打开应用

### ISSUE THREAD

**Issue by VanishingDante** [trazyn/weweChat#23]
无法接收消息，无法发送消息

**Comment by trazyn** [comment]
webwxbatchgetcontact 这个接口出现1205时候通常会这样，此时web.wechat.com也会登陆不上，目前还不清楚这个返回是什么原因造成的

**Comment by trazyn** [comment]
同 #17 ，增加了心跳的超时检测
