### ISSUE TITLE
Ubuntu 20.04 Segmentation Fault

### ISSUE THREAD

**Issue by matthewwen** [trazyn/weweChat#250]
./wewechat-1.1.6-linux-x86_64.AppImage 
Segmentation fault (core dumped)

This includes 1.1.7 and the deb version.

**Comment by zhbotong** [comment]
在Manjaro中也有这个问题

**Comment by abc66099** [comment]
重新打包一下就好了

**Comment by PigeonAOA** [comment]
没有解决
