### ISSUE TITLE
关于发送图片问题

### ISSUE THREAD

**Issue by StarkChristmas** [trazyn/weweChat#256]
你们编译完可以发送图片吗？我的无论什么平台上都没发发送图片

**Comment by Catiks** [comment]
都已经不维护了

**Comment by StarkChristmas** [comment]
是的，遗憾，希望Tencent能在linux上支棱起来

**Comment by kangxiaoju** [comment]
https://github.com/trazyn/weweChat/issues/193#issuecomment-435242051
