### ISSUE TITLE
打包成安装包错误，下载不来winCodeSign

### ISSUE THREAD

**Issue by yoke1990** [trazyn/weweChat#26]
程序已经生成好了，就是自动打包这个出错了
这个应该是win签名的包winCodeSign，下载不了。

electron-builder 19.27.3
No native production dependencies
Packaging for win32 ia32 using electron 1.6.11 to ..\release\win-ia32-unpacked
⚠️  Application icon is not set, default Electron icon will be used
Downloading winCodeSign-1.9.0, please wait
**⚠️  Cannot download winCodeSign, attempt #1: Error: Request timed out**
Error: connect ETIMEDOUT 54.231.40.3:443
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\Users\Yoke\weweChat\node_modules\_bluebird@3.5.0@bluebird\js\release\debuggability.js:397:19)
    at new PromiseSpawn (C:\Users\Yoke\weweChat\node_modules\_bluebird@3.5.0@bluebird\js\release\generators.js:43:17)
    at C:\Users\Yoke\weweChat\node_modules\_bluebird@3.5.0@bluebird\js\release\generators.js:197:21
    at NodeHttpExecutor.download (C:\Users\Yoke\weweChat\node_modules\_builder-util@1.0.1@builder-util\out\nodeHttpExecutor.js:159:11)
    at Timeout._onTimeout (C:\Users\Yoke\weweChat\node_modules\_builder-util@1.0.1@builder-util\src\binDownload.ts:85:39)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! wewechat@1.1.0 package-win32: `npm run build && build --win --ia32 --projectDir ./dist`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the wewechat@1.1.0 package-win32 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Yoke\AppData\Roaming\npm-cache\_logs\2017-09-04T09_56_53_132Z-debug.log

**Comment by trazyn** [comment]
国内老实用cnpm吧 国内网络因为众所周知的原因是无法访问一些外网的

**Comment by yoke1990** [comment]
cnpm 也不行/(ㄒoㄒ)/~~

**Comment by trazyn** [comment]
多试几次，或者挂ss或者未批恩，fq是国内程序员的必备技能之一

**Comment by yoke1990** [comment]
https://cnpmjs.org
https://npm.taobao.org
进入网站直接搜包，也搜不到winCodeSign
npm源我切换过了，cnpm也试过

**Comment by trazyn** [comment]
这个是electron-builder的依赖，网络问题可以参考科学上网系列

**Comment by yoke1990** [comment]
我查下它依赖看下情况。

**Comment by zzhgithub** [comment]
手动下载吧.大兄弟 — https://github.com/electron-userland/electron-builder-binaries/releases/tag/winCodeSign-1.9.0

**Comment by baochunliang** [comment]
@zzhgithub 请问手动下载后，放哪里呢。

**Comment by zzhgithub** [comment]
macOS: ~/Library/Caches/electron-builder
Linux: ~/.cache/electron-builder
windows: %LOCALAPPDATA%\electron-builder\cache

**Comment by songlingxi** [comment]
@zzhgithub 你好, 我在 %LOCALAPPDATA%\electron-builder\cache 下新建了 winCodeSign 文件夹, 并将7z中的文件复制进去. 结果打包时还是会去下载... 请问这个怎么破?

**Comment by trazyn** [comment]
换个好点的网络就能直接安装了，没办法近期狮鹫大各种网络问题

**Comment by songlingxi** [comment]
@trazyn 已经尝试过科学上网的方法了 (/ □ \)

**Comment by trazyn** [comment]
我每次都能下载成功没碰到过😅

**Comment by yanjingenious** [comment]
就像楼上说的，多试几次就好了，你还可以看看package.json里的配置https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#options
上面文档中有个download的配置具体可以试试

**Comment by nickyang86** [comment]
各位，这个问题也困扰我很久，解决方法参考如下：http://www.cnblogs.com/chenweixuan/p/7693718.html，特别注意是在C:\Users\Administrator\AppData\Local\electron-builder\cache路径下要先建winCodeSign，在把下载的winCodeSign-1.9.0整个文件夹放进去，nsis与nsis-resources同样操作就可以打包成功。
nsis-resources-3.3.0：https://github.com/electron-userland/electron-builder-binaries/releases/tag/nsis-resources-3.3.0，
nsis-3.0.1.13：https://github.com/electron-userland/electron-builder-binaries/releases/tag/nsis-3.0.1.13，
winCodeSign-1.9.0：https://github.com/electron-userland/electron-builder-binaries/releases/tag/winCodeSign-1.9.0

**Comment by leoskey** [comment]
> 各位，这个问题也困扰我很久，解决方法参考如下：[http://www.cnblogs.com/chenweixuan/p/7693718.html，特别注意是在C:\Users\Administrator\AppData\Local\electron-builder\cache路径下要先建winCodeSign，在把下载的winCodeSign-1.9.0整个文件夹放进去，nsis与nsis-resources同样操作就可以打包成功。](http://www.cnblogs.com/chenweixuan/p/7693718.html%EF%BC%8C%E7%89%B9%E5%88%AB%E6%B3%A8%E6%84%8F%E6%98%AF%E5%9C%A8C:%5CUsers%5CAdministrator%5CAppData%5CLocal%5Celectron-builder%5Ccache%E8%B7%AF%E5%BE%84%E4%B8%8B%E8%A6%81%E5%85%88%E5%BB%BAwinCodeSign%EF%BC%8C%E5%9C%A8%E6%8A%8A%E4%B8%8B%E8%BD%BD%E7%9A%84winCodeSign-1.9.0%E6%95%B4%E4%B8%AA%E6%96%87%E4%BB%B6%E5%A4%B9%E6%94%BE%E8%BF%9B%E5%8E%BB%EF%BC%8Cnsis%E4%B8%8Ensis-resources%E5%90%8C%E6%A0%B7%E6%93%8D%E4%BD%9C%E5%B0%B1%E5%8F%AF%E4%BB%A5%E6%89%93%E5%8C%85%E6%88%90%E5%8A%9F%E3%80%82)
> nsis-resources-3.3.0：[https://github.com/electron-userland/electron-builder-binaries/releases/tag/nsis-resources-3.3.0，](https://github.com/electron-userland/electron-builder-binaries/releases/tag/nsis-resources-3.3.0%EF%BC%8C)
> nsis-3.0.1.13：[https://github.com/electron-userland/electron-builder-binaries/releases/tag/nsis-3.0.1.13，](https://github.com/electron-userland/electron-builder-binaries/releases/tag/nsis-3.0.1.13%EF%BC%8C)
> winCodeSign-1.9.0：https://github.com/electron-userland/electron-builder-binaries/releases/tag/winCodeSign-1.9.0

nsis-resources-3.3.0 需要放置在 nisi 文件夹。

**Comment by 1c7** [comment]
## 方法2：
直接给命令行设置代理
```
set http_proxy=http://127.0.0.1:2802
set https_proxy=http://127.0.0.1:2802
```

(windows 本地在 2802 端口跑了代理)
