### ISSUE TITLE
文件传输助手不能用

### ISSUE THREAD

**Issue by almas1992** [trazyn/weweChat#27]
* 系统：Ubuntu 16.04LTS
* 软件版本：1.1.1

试了好几次，用手机上的文件传输助手发送信息，客户端收不到信息

**Comment by trazyn** [comment]
目前代码里面吧所有公众号和品牌账号（京东之类）给屏蔽了，后面会放出文件助手

**Comment by almas1992** [comment]
@trazyn 登录后，用手机端给好友发信息也会有 notifaction；
觉得收到信息时在挂后台才有notifaction好点，现在是收到发送都有notifaction。

**Comment by trazyn** [comment]
嗯现在代码确实是这样的，自己发送的消息同步到客户端上有提示
