### ISSUE TITLE
可以增加一个隐藏菜单栏的选项吗？

### ISSUE THREAD

**Issue by imzf** [trazyn/weweChat#28]
如题，有菜单栏很不美观，记得最初的版本是没菜单栏的
![default](https://user-images.githubusercontent.com/3401994/30247918-ab0f2d5c-9650-11e7-95a4-06ec26d5f565.png)

**Comment by trazyn** [comment]
linux？

**Comment by imzf** [comment]
@trazyn 没错，就是linux

**Comment by trazyn** [comment]
嗯 晚点打包上去
