### ISSUE TITLE
The emoji in contact's name cannot be displayed normally when browsing contacts from menu bar.

### ISSUE THREAD

**Issue by muzikmoe** [trazyn/weweChat#29]
`usr_name [emoji]` is displayed as:
`usr_name <span class="emoji emoji1f370></span>`
the emoji is not rendered.

----------
AppVersion: wewechat-1.1.1-x86_64.AppImage
OS: Linux
Distributor ID:	ManjaroLinux
Release:	17.0.4
Codename: Gellivara
Kernel: 4.13.0-1-MANJARO

**Comment by trazyn** [comment]
emoji在微信的服务器上转义了以便在其他系统下能正常显示，在对应系统下再转义成具体的emoji 工作量会比较大啊

**Comment by trazyn** [comment]
will replace html on osx

**Comment by muzikmoe** [comment]
ok, I set a custom alias name for these contacts.
Thank for your great work anyway.

**Comment by trazyn** [comment]
done
