### ISSUE TITLE
对于自动更新这块有研究吗？

### ISSUE THREAD

**Issue by xp6530** [trazyn/weweChat#31]

**Comment by trazyn** [comment]
https://www.electron.build/auto-update
目前主要在改bug和优化，不准备加新功能

**Comment by trazyn** [comment]
1.1.2 已增加

**Comment by gclsoft** [comment]
@trazyn 您是怎么判断新版本的, 通过哪个url去检查, 代码里看不出来 https://github.com/trazyn/weweChat/commit/2d3f8060f8f6cbc3593ba32c07f3e41febeca312

**Comment by gclsoft** [comment]
@trazyn 这个是electron-builder项目的代码, weweChat这个项目是通过哪个url去判断是否该更新了?

**Comment by trazyn** [comment]
electron-builder拿到配置在package.json 中的 publish信息生成 app-update.yml ，provider 以 github 为例检查 release  找对应的 last-platform.yml，剩下的顺着上面回复代码看就好

**Comment by gclsoft** [comment]
@trazyn 谢谢,如果不用github做判断, 以自己的服务器做更新判断要怎么改呢? 更新文件也是保存在自己的服务器上的

**Comment by trazyn** [comment]
可以参考这里：
https://www.electron.build/configuration/publish#genericserveroptions
https://www.electron.build/file-patterns#file-macros
