### ISSUE TITLE
退出后，登录信息能保存

### ISSUE THREAD

**Issue by flyfei** [trazyn/weweChat#33]
如果程序退出，再次启动时，显示之前登录过的账号，和“登录”按钮

这样的话，就不需要每次都扫码了

**Comment by trazyn** [comment]
嗯 晚点看看

**Comment by trazyn** [comment]
网页上那个直接显示登陆什么情况下出来啊，试了下手机退出上面都是直接就显示二维码了

**Comment by flyfei** [comment]
sorry，我也不知道咋弄出来....

**Comment by trazyn** [comment]
现在是只要session还没有过期就会自动登录

**Comment by flyfei** [comment]
嗯嗯，辛苦

**Comment by levinit** [comment]
@trazyn 我还以为是微信支持保存登录信息了呢……  网页版一关就要重新扫码 很是烦人
