### ISSUE TITLE
操作略卡顿 消息推送稍慢 Icon

### ISSUE THREAD

**Issue by eagrex** [trazyn/weweChat#34]
感谢！独树一帜的第三方WeChat客户端！
不过在我的rmbp2017上操作略卡顿 推送也稍慢 不知道后续能否优化？
另外，这个icon是有点神奇哈哈！
如果有更新图标的计划，我可以尝试做一个～
最后，开发棒棒哒！

**Comment by trazyn** [comment]
我也是rmbp2017 操作卡顿这个是在什么场景下面呢，图标是临时高的，1.2做静态网站会换掉，最近wechat主要修复bug和找bug顺便弄网易云估计骚骚晚一点

**Comment by trazyn** [comment]
应该是 #36 的问题，显示用户头像到菜单导致

**Comment by icybest** [comment]
我在MacBook使用macOS和台式上使用window都会出现操作卡顿，尝试复原了一下操作场景，短时间内频繁的切换聊天对象也就是在左侧不停的上下点不同的聊天对象就会开始卡顿，后面所有操作都卡顿。不知道是不是个例。

**Comment by trazyn** [comment]
@icybest 1.1.1增加了头像到菜单栏，每次对话变化后都会将头像转换dataURL发送到main进程导致的卡顿和占用内存

**Comment by trazyn** [comment]
done

**Comment by howie6879** [comment]
借issue提下我遇到的类似问题 发消息略卡顿 一个消息 敲enter键快点的话就会把一个消息发出去两次
![selection_003](https://user-images.githubusercontent.com/17047388/30676598-70e80a9c-9eb9-11e7-9150-efdf94bfcf27.png)

**Comment by trazyn** [comment]
用的是哪个版本啊

**Comment by trazyn** [comment]
@howie6879 加号是创建会话，如果隐藏掉的的话就只能快捷键打开了，感觉不太直观

**Comment by trazyn** [comment]
@howie6879 已修复，谢谢反馈

**Comment by howie6879** [comment]
@trazyn 不客气 开发才辛苦了 加号那个只是个人看着不习惯 创建会话我用的不多 是否可让用户自己可选隐藏呢   若不行也可以

**Comment by trazyn** [comment]
@howie6879 可以
