### ISSUE TITLE
内存占用

### ISSUE THREAD

**Issue by a5867460** [trazyn/weweChat#36]
- Ubuntu 16.14 64bit
- Kernel: 4.4.0-93-generic

- 随开启时间增加内存缓慢增加，目测接收到新的消息会引起增长

**Comment by trazyn** [comment]
收到的信息会一直保存的这些确实是会占用内存

**Comment by a5867460** [comment]
哦哦，我的机器是8G，开了大概半天的时间会占用2个多G，感觉可以考虑对长时间不阅读的对话信息持久化到硬盘，从内存里移出去吧，需要的时候再进行读取

**Comment by trazyn** [comment]
这个情况看起来应该是菜单栏显示用户头像导致的（mac上菜单会显示联系人头像）

**Comment by a5867460** [comment]
明白,卡顿的状况的确是在切换聊天的时候有,我以为只是过渡动画没有完善导致的...

**Comment by trazyn** [comment]
1.1.3 试试

**Comment by trazyn** [comment]
更新菜单时候创建nativeimage显示头像导致内存使用过高，加了缓存避免了频繁创建naviveimage实例了

**Comment by trazyn** [comment]
![screen shot 2017-09-19 at 8 04 41 pm](https://user-images.githubusercontent.com/1774898/30591553-d8f0d6fe-9d75-11e7-8140-d1e2c7a3c5cc.png)
对比了下官方的，登陆wewechat的加了8个游戏群刷消息，另外个加了2个群，现在应该是正常没问题了

**Comment by a5867460** [comment]
恩 目前使用过程中没有这个问题了
