### ISSUE TITLE
打字时会出现输入法选词框，偏离到界面左上角的情况

### ISSUE THREAD

**Issue by Yu-Wu** [trazyn/weweChat#38]
类似下面这种
<img width="740" alt="2017-09-24 2 42 45" src="https://user-images.githubusercontent.com/24566764/30779551-ff541670-a136-11e7-8a7d-dd595edce800.png">

**Comment by trazyn** [comment]
目前这windows 和 linux 个上样式没怎么去适配，所以有些地方显示可能会有问题

**Comment by Yu-Wu** [comment]
@trazyn 多谢回复。我用的是Mac os10.12。不过好像就我遇到了这个问题

**Comment by trazyn** [comment]
额 确实没碰到过这个问题，我的也是 10.12， 你用的什么输入法啊 我试试

**Comment by desirelll** [comment]
我也遇到这个问题…
搜狗输入法…

**Comment by gordon-rawe** [comment]
你这个问题是electron的版本的问题，升级electron的版本到1.8.x可以解决这个问题
