### ISSUE TITLE
能不能更改应用程序的图标？感觉那个啃西瓜的图标不是很好看，可以自己去修改吗？

### ISSUE THREAD

**Issue by Yu-Wu** [trazyn/weweChat#39]
能不能更改应用程序的图标？感觉那个啃西瓜的图标不是很好看，可以自己去修改吗？

**Comment by trazyn** [comment]
额 图标随便弄的，我也想换一个呢
Mac 上改图标很简单的，先吧要换的图标 `CMD + C` 复制到剪切板，然后在应用上面 `CMD + I` 选中小图标 `CMD + V` 就搞定了
![screen shot 2017-09-24 at 2 50 54 pm](https://user-images.githubusercontent.com/1774898/30780183-cc5ef20c-a137-11e7-92fa-6b6915ebfdf7.png)

**Comment by trazyn** [comment]
我找隔壁项目图标的作者搞搞吧

**Comment by HiKWang** [comment]
请问ubuntu上怎么改图标呢？现在图标就是系统默认的问号

**Comment by trazyn** [comment]
@HiKWang 用的少，我也不知道怎么改linux的图标😂

**Comment by androidcn** [comment]
这图标确实不好

**Comment by imzf** [comment]
@HiKWang @trazyn linux图标很容易修改的
方法1.删除~/.local/share/icons/hicolor所有子目录中名为appimagekit-wewechat的图片，下载你喜欢的图标文件（我个人推荐svg），修改文件名为appimagekit-wewechat（保留扩展名），并将其复制到~/.local/share/icons/目录
![default](https://user-images.githubusercontent.com/3401994/31053795-d413e908-a6d7-11e7-94cf-f39301c67ac1.png)

方法二，如果你想使用你安装的图标主题包中的图标，例如我使用的是elementary图标包，聊天软件对应的图标名为internet-chat,则修改~/.local/share/applications/appimagekit-wewechat.desktop中Icon=internet-chat

![default](https://user-images.githubusercontent.com/3401994/31053818-368d0916-a6d8-11e7-9008-f607725cd832.png)

**Comment by jingle0927** [comment]
支持改个图标

**Comment by trazyn** [comment]
![128x128](https://user-images.githubusercontent.com/1774898/31760950-f60f6a4a-b4e8-11e7-9698-b3f3ba5e56ab.png)
新图标
