### ISSUE TITLE
Search 输入群名找不到

### ISSUE THREAD

**Issue by flyfei** [trazyn/weweChat#43]
Hello，在搜索框里输入 群名，有的群（没有保存到通讯录中的群）找不到

**Comment by trazyn** [comment]
旅游中，抽空调整下代码

**Comment by flyfei** [comment]
Cool,好好玩

**Comment by trazyn** [comment]
search时候搜索范围是会话列表和通讯录，如果在会话列表和通讯录中都不存在的话是找不到的
