### ISSUE TITLE
ubuntu14.04 forward message功能bug

### ISSUE THREAD

**Issue by howie6879** [trazyn/weweChat#57]
发送图片无反应，text消息可以，如图：
![selection_001](https://user-images.githubusercontent.com/17047388/31699418-96ee08e4-b3f5-11e7-9f6d-789e695f61e3.png)

**Comment by trazyn** [comment]
控制台有报错么

**Comment by howie6879** [comment]
1.转发图片无报错，不成功，还有聊天框的图不能点击不能放大查看么？
2.无法打开小视频，错误如下：
![selection_002](https://user-images.githubusercontent.com/17047388/31702383-51d358e0-b409-11e7-9f56-b86c659d037b.png)

**Comment by trazyn** [comment]
1. 聊天框的图片是有两种的一种是`表情`另外一种才是`图片`，图片是能直接打开的，会调用系统默认的preview
2. `web api`里面有些视频是有限制的只能看到预览图而无法正常播放，这个可能需要重新抓下其他客户端的包

**Comment by howie6879** [comment]
嗯嗯  明白了

**Comment by xiyionxiong** [comment]
@howie6879 请问你在ubuntu下 是否可以发送文件大小大于1M的文件？
