### ISSUE TITLE
Checksum  does not match.

### ISSUE THREAD

**Issue by catbaron0** [trazyn/weweChat#58]
I met an error when I tried to install it with `brew cask`

> Error: Checksum for Cask 'wewechat' does not match.
>
> Expected: bcd11208cfe037113c1efcc6eb156ac3e3998dcd8e8b444d0ccc0ea2aa1cc9ec
> Actual:   80a6155085f1dfe5685610e4ff84a6bc60d297787578dba22a5f8991a82255b3

Please check it when you're free.

**Comment by trazyn** [comment]
thanks for your feedback

**Comment by trazyn** [comment]
Already update
