### ISSUE TITLE
右下消息提示框是如何实现的？

### ISSUE THREAD

**Issue by li986390329** [trazyn/weweChat#62]
最近在研究弹出一个像QQ那样的新消息来了的消息提示框，不过觉得weweChat这个消息提示也很好看，所以想问下，是如何实现的，希望不吝赐教，十分感谢。

**Comment by trazyn** [comment]
使用的是notification 可以参考chat.js

**Comment by li986390329** [comment]
十分感谢，已经知道了

**Comment by gclsoft** [comment]
@trazyn 为什么我几台电脑试了都不能弹出消息提示框, win10系统
![image](https://user-images.githubusercontent.com/1269898/44011988-a1f05c4e-9eee-11e8-92e7-fa24af3bb30b.png)
