### ISSUE TITLE
如何压缩打包

### ISSUE THREAD

**Issue by w446108264** [trazyn/weweChat#63]
冒昧请教一下作者
electron打包出50多M，非常好的结果
请问使用什么方式压缩打包的呢
@trazyn

**Comment by trazyn** [comment]
打包使用的是electron-builder，配置可以参考package.json

**Comment by w446108264** [comment]
没有使用upx之类的加壳压缩处理吗，我用electron-builder直接打包demo都是100m+😂

**Comment by trazyn** [comment]
没有啊

**Comment by w446108264** [comment]
var.darling@gmail.com 这个是你的邮箱吗
