### ISSUE TITLE
在Linux下隐藏标题栏

### ISSUE THREAD

**Issue by patrick330602** [trazyn/weweChat#73]
现在在Linux下的界面（估计Windows也是）有两个标题栏。。。感觉怪怪的，希望加一个选项可以开关

**Comment by trazyn** [comment]
你的桌面环境是什么

**Comment by patrick330602** [comment]
用的gnome 3.26, ubuntu 17.10

**Comment by x1314aq** [comment]
ubuntu 16.04也出现了两个标题栏的情况

**Comment by thinkiny** [comment]
没有解决呀，现在还是两个标题栏
