### ISSUE TITLE
关于发送文件的问题。

### ISSUE THREAD

**Issue by xiyionxiong** [trazyn/weweChat#74]
目前发现，文件大小到一定范围就不能发送了。 
我是android开发，需要发送apk文件，这一点希望能改进。
或者是我的使用姿势不对，请告之。

**Comment by trazyn** [comment]
微信发送文件大小限制在50M，超过50是不能发送的

**Comment by xiyionxiong** [comment]
我这发2-3M的文件都是失败的。

**Comment by trazyn** [comment]
发送文件报的是什么错？有些文件是被禁止的无法上传[比如这个里面的很多东西就无法上传](https://github.com/programthink/zhao)

**Comment by xiyionxiong** [comment]
@trazyn 報錯信息如下  ：  

 
![1](https://user-images.githubusercontent.com/14977994/33246807-19d389aa-d354-11e7-90bd-27611f945e03.png)
<br/>
![2](https://user-images.githubusercontent.com/14977994/33246810-23808a5c-d354-11e7-8b34-0043ba9f2f03.png)
<br/>

另： 发送的文件 不在 禁止的范围。 普通的pdf 文件大小 > 1m 就回出错。
使用环境为：ubuntu17.10 x64 .
 谢谢。

**Comment by trazyn** [comment]
#78 Web端微信要被和谐了

**Comment by trazyn** [comment]
试了下现在应该是需要分片了

**Comment by xiyionxiong** [comment]
不太明白 分片什么意思？

**Comment by trazyn** [comment]
下载最新的1.1.5
