### ISSUE TITLE
It seems that Wechat will no longer support web version.

### ISSUE THREAD

**Issue by livc** [trazyn/weweChat#78]
![](https://i.loli.net/2017/11/25/5a18e231280ee.jpg)

image from <https://github.com/blueset/ehForwarderBot> Telegram Support Group.

**Comment by trazyn** [comment]
GGGGG

**Comment by sxft1978** [comment]
腾讯看来特别讨厌linux用户,trazyn辛苦啦

**Comment by aforwardz** [comment]
同志们，gg了，之前用这个被封了，一直没给解决。刚打客服，客服已经确定网页版要下架了，Linux已经。。

**Comment by sxft1978** [comment]
看来linux以后没有wechat桌面端了
