### ISSUE TITLE
在deepin下托盘显示的不是logo图标

### ISSUE THREAD

**Issue by jingle0927** [trazyn/weweChat#79]

**Comment by jingle0927** [comment]
![_ _20171127154303](https://user-images.githubusercontent.com/26103116/33255671-aef3a4cc-d389-11e7-8a0e-1db1ab55bcd4.png)

**Comment by jingle0927** [comment]
而且双击托盘图标不出现主界面。

**Comment by trazyn** [comment]
显示的是`tray icon`并不是应用`logo`

**Comment by jingle0927** [comment]
@trazyn 不能优化吗

**Comment by jingle0927** [comment]
http://packages.deepin.com/deepin/pool/non-free/w/wewechat/ 已经准备上架了，现在在仓库，可以的话 优化下 tray icon

**Comment by trazyn** [comment]
直接把包里面的那个黑色的替换掉就行啊
