### ISSUE TITLE
Linux，Gnome3. 通知栏没显示图标

### ISSUE THREAD

**Issue by XanthusL** [trazyn/weweChat#8]
希望聊天记录中能显示通过移动端发送的消息

**Comment by trazyn** [comment]
弹二维码大概是账号原因被服务器断开然后重新刷新要求登录了，可以打开devtools查看下错误信息

**Comment by XanthusL** [comment]
弹二维码应该是刚才不小心开了多个进程，又试了试没复现<br>
但是通知栏没图标，窗口关了就没地方打开了:joy:

**Comment by trazyn** [comment]
linux 和 window 上应调整代码为默认显示小图标，并禁用设置里面的switch按钮，没linux电脑，有空你可以自己加上去然后pr过来

**Comment by XanthusL** [comment]
好吧，不熟悉JS，react、electron也只是了解<br>:joy:有空我强行看看代码

**Comment by XanthusL** [comment]
当前版本临时解决办法，
在设置中打开`show on tray`通知栏就有图标了
不过通知栏中的图标单击无效，得在右击的菜单中选`toggle main window`

**Comment by trazyn** [comment]
嗯 现在 左右键都是弹出菜单，等下我吧左键调整为显示主窗口

**Comment by trazyn** [comment]
window和linux上目前修改为始终显示小图标了
