### ISSUE TITLE
mac和手机微信消息不同步

### ISSUE THREAD

**Issue by thomasyxy** [trazyn/weweChat#9]
手机上自己给自己发的消息没有显示出来 :)

**Comment by thomasyxy** [comment]
好吧~ 原来是手机上发的消息不会同步。。。
这个能做得到吗？

**Comment by trazyn** [comment]
给自己发消息和手机上发消息同步到客户端可以做
通知栏那个暂时没测试出来，消息不屏蔽都显示出来了

**Comment by trazyn** [comment]
[receive message from yourself](https://github.com/trazyn/weweChat/commit/b3547f75f17e70de5df8a9996f661d59bd8afb8c)
[sync the message of your sent to client](https://github.com/trazyn/weweChat/commit/f4a4d51a5d4062c0a05ea4218df10670ade9f1a6)
试试

**Comment by thomasyxy** [comment]
可以了 真效率啊~

**Comment by franktang** [comment]
似乎某些情况对方发的微信在mac端也看不到，但是手机端就能看到

**Comment by trazyn** [comment]
@franktang 嗯 有时候确实有这个问题，目前在尝试重现问题
