### ISSUE TITLE
Support for Moments?

### ISSUE THREAD

**Issue by lynnard** [trazyn/weweChat#98]
Thanks for the excellent work :)

Is there any planned support for Moments? (Is that even possible with the web wechat api..?)

Thank you.

**Comment by trazyn** [comment]
No moments api for web

**Comment by lynnard** [comment]
Alright, thanks for confirmation. (Would be nice if they support that though, or maybe someone can reverse engineer the api from the apps themselves; but until then there isn't too much we can do I suppose)
